//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilitySale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        public int CheckID { get; set; }
        public int peopleID { get; set; }
        public string Checknumber { get; set; }
        public string CheckDate { get; set; }
        public string CheckBank { get; set; }
        public Nullable<long> CheckPrice { get; set; }
        public string CheckType { get; set; }
        public string CheckDesc { get; set; }
    
        public virtual People People { get; set; }
    }
}
