//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilitySale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSuply
    {
        public int ProductSuplyID { get; set; }
        public int ProductID { get; set; }
        public Nullable<int> ProductSuplyIN { get; set; }
        public string ProductSuplyStatus { get; set; }
        public string ProductSuplyDesc { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
