//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilitySale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Invoice2
    {
        public int InvoiceID { get; set; }
        public string InvoiceDate { get; set; }
        public Nullable<long> InvoicePricenottax { get; set; }
        public long InvoicePrice { get; set; }
        public int peopleID { get; set; }
        public string InvoiceDesc { get; set; }
        public string PeopleName { get; set; }
    }
}
