//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilitySale.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Items
    {
        public string ProductName { get; set; }
        public int InvoiceItemID { get; set; }
        public int InvoiceItemcount { get; set; }
        public long InvoiceItemFee { get; set; }
        public long InvoiceItemFeeTotal { get; set; }
        public int ProductID { get; set; }
        public int InvoiceID { get; set; }
    }
}
